server:
  port: 8080

spring:
  application:
    name: api-gateway
 

zuul:
  ignored-headers: Access-Control-Allow-Credentials, Access-Control-Allow-Origin
  addProxyHeaders: true
  routes:
   
    connector-service:
      path: /no-crm/**
      serviceId: no-crm
