server:
  port: 8080

spring:
  application:
    name: api-gateway
  http:
    multipart:
      max-file-size: 400Mb
      max-request-size: 1000Mb
  cloud:
    stream:
      bindings:
        apiLogRecordChannel:
          destination: apiLogRecordChannel
          contentType: application/json
          mappedRequestHeaders: "*"

zuul:
  ignored-headers: Access-Control-Allow-Credentials, Access-Control-Allow-Origin
  addProxyHeaders: true
  routes:
   
    connector-service:
      path: /no-crm/**
      serviceId: no-crm
