spring:
  profiles:
    active: dev
server:
  jpa:
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        ddl-auto: update
        format_sql: true
      eclipse:
        persistence:
          context:
            flush-mode: COMMIT
          weaving: false
          ddl-generation: none
      query-results-cache: false
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      idle-timeout: 10000
      maximum-pool-size: 15
    platform: mysql
    username: root
    password: NavaBrind@123
    driver-class-name: com.mysql.cj.jdbc.Driver
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    registryFetchIntervalSeconds: 10
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    registerWithEureka: true
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 10
