spring:
  profiles:
    active: dev
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    registryFetchIntervalSeconds: 10
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    registerWithEureka: true
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 10
