spring:
  application:
    name: no-crm
server:
  port: 8001
  jpa:
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        ddl-auto: update
        format_sql: true
      eclipse:
        persistence:
          context:
            flush-mode: COMMIT
          weaving: false
          ddl-generation: none
      query-results-cache: false
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      idle-timeout: 10000
      maximum-pool-size: 15
    platform: mysql
    username: root
    password: NavaBrind@123
    url: jdbc:mysql://localhost:3306/java_no_crm_db?useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver

logging:
  appender: logstash
  level:
    root: DEBUG
    org:
      springframework:
        data: DEBUG
      hibernate: DEBUG
      apache: DEBUG
    com:
      contiq: DEBUG
      common:
        MultiTenantJpaTransactionManager: OFF
      hibernate:
        tool:
          hbm2ddl:
            SchemaExport: OFF



#logging:
#  level:
#    root: DEBUG
#    org:
#      springframework:
#        data: DEBUG
#      hibernate: DEBUG
#      apache: DEBUG
#    com:
#      contiq: DEBUG
#      common:
#        MultiTenantJpaTransactionManager: OFF
#      hibernate:
#        tool:
#          hbm2ddl:
#            SchemaExport: OFF

